version: '3'
services:
  hybrid-blog:
    build:
      context: .
    ports:
      - "8000:3000"
    container_name: hybrid-blog
    stdin_open: true
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules