version: '3'
services:
  breakingbad:
    build:
      context: .
    ports:
      - "8000:3000"
    container_name: breakingbad
    stdin_open: true
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules